export const FETCH_CASES_LOADING = "FETCH_CASES_LOADING"
export const FETCH_CASES_SUCCESS = "FETCH_CASES_SUCCESS"
export const FETCH_CASES_FAILURE = "FETCH_CASES_FAILURE"

export const FETCH_DISTRICT_CASES_LOADING = "FETCH_DISTRICT_CASES_LOADING"
export const FETCH_DISTRICT_CASES_SUCCESS = "FETCH_DISTRICT_CASES_SUCCESS"
export const FETCH_DISTRICT_CASES_FAILURE = "FETCH_DISTRICT_CASES_FAILURE"

export const SORT_CASES = "SORT_CASES"
export const SEARCH_CASES = "SEARCH_CASES"